name: Release (Private Packages)
on:
  workflow_dispatch:

jobs:
  version_or_release:
    name: 'Version and open PR (or) release private packages'
    runs-on: ubuntu-latest
    environment: 'Production - Private Packages'
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 7.5.0 
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
     
    
     
